create table if not exists bookuser (
    id bigint generated by default as identity,
    username varchar(50),
    password varchar(50),
    role varchar(10),
    realname varchar(50),
    email varchar(150),
    address varchar(250)
);
create table if not exists bookinfo (
    id bigint generated by default as identity,
    name varchar(50),
    fmimg longtext,
    author varchar(10),
    price varchar(50),
    intro text
);

create table if not exists bookitem (
    id bigint generated by default as identity,
    orderid varchar(50),
    bookid bigint,
    name varchar(50),
    fmimg longtext,
    price varchar(50),
    num bigint,
    pertotal varchar(10),
    intro text
);

create table BOOKINFO
(
    ID     INTEGER auto_increment,
    NAME   CHARACTER VARYING(150),
    FMIMG  CHARACTER VARYING,
    AUTHOR CHARACTER VARYING(50),
    PRICE  CHARACTER VARYING(50),
    INTRO  CHARACTER VARYING
);